version: '3.9'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    networks:
      - app-network

  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/mydb?schema=public
      JWT_SECRET: your_jwt_secret
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USER: vovayhh9988@gmail.com
      SMTP_PASS: kdvf mlgm rdpu vvky
      EMAIL_FROM: "No Reply <vovayhh9988@gmail.com>"
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db-data: {}
  
networks:
  app-network:
    driver: bridge
